# Generated by Django 4.1.3 on 2023-10-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='icon',
            field=models.CharField(default='fa fa-tasks', max_length=50),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='vacancy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
